export const UPDATE_NAME = "PERSONAGE/UPDATE_NAME";
export const UPDATE_PERSONAGE = "PERSONAGE/UPDATE_PERSONAGE";
export const UPDATE_BASE_PARAMETRS = "PERSONAGE/UPDATE_BASE_PARAMETRS";
export const UPDATE_CHARACTERISTIC = "PERSONAGE/UPDATE_CHARACTERISTIC";
export const UPDATE_POWER_SKILLS = "PERSONAGE/UPDATE_POWER_SKILLS";
export const UPDATE_AGILITY_SKILLS = "PERSONAGE/UPDATE_AGILITY_SKILLS";
export const UPDATE_INTELIGENCE_SKILLS = "PERSONAGE/UPDATE_INTELIGENCE_SKILLS";
export const UPDATE_CHARISMA_SKILLS = "PERSONAGE/UPDATE_CHARISMA_SKILLS";
export const RECEIVED_DAMAGE = "PERSONAGE/RECEIVED_DAMAGE";

export const RECEIVED_DAMAGE_SHOW = "APP/RECEIVED_DAMAGE_SHOW";
export const RECEIVED_DAMAGE_HIDE = "APP/RECEIVED_DAMAGE_HIDE";
